server:
    port: 9000
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: false
    profiles:
        active: @spring.profiles.active@
    config:
        import:
            - "application_qa.yml"
            - "application_prod.yml"

build:
    version: "3.0"

cards:
    message: "Microservice for Cards. Environment: DEFAULT"
    contactDetails:
        name: "Marcosxx1"
        email: "marcosxx1.ma@gmail.com"
    onCallSuport:
        - (XX) XXX-XXX1
        - (XX) XXX-XXX2