# Use a multi-stage build to reduce final image size
FROM openjdk:17-jdk-slim AS build
WORKDIR /app
COPY target/accounts-0.0.1-SNAPSHOT.jar /app

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/accounts-0.0.1-SNAPSHOT.jar"]


# docker build . -t marcossata/accounts:s4
# list:  docker images OU docker ps -a
# run accounts: docker run -d  -p 8080:8080 marcossata/accounts:s4

# Stop and remove the container(s) using the image:

# docker stop <container_id>
# docker rm <container_id>