services:
    accounts:
        image: marcossata/accounts:s4 # Que subimos no Docker.io hub
        container_name: accounts-ms
        ports:
            - "8080:8080"
            #- Podemos definir várias portas para o serviço
        deploy:
            resources:
                 limits:
                     memory: 700m
        networks:
            - bankApplication # Rede interna que os serviços vão se comunicar

    loans:
        image: marcossata/loans:s4
        container_name: loans-ms
        ports:
            - "8090:8090"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication

    cards:
        image: marcossata/cards:s4
        container_name: cards-ms
        ports:
            - "9000:9000"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication
networks:
    bankApplication: # Rede interna que os serviços vão se comunicar
        driver: "bridge"