# Use a multi-stage build to reduce final image size
FROM openjdk:17-jdk-slim AS build
WORKDIR /app
COPY target/accounts-0.0.1-SNAPSHOT.jar /app

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/accounts-0.0.1-SNAPSHOT.jar"]
