version: '3.8'

services:
    accounts:
        build:
            context: ./accounts  # Points to the accounts directory
            dockerfile: Dockerfile.accounts  # Dockerfile within the accounts directory
        image: marcossata/accounts:s4
        container_name: accounts-ms
        ports:
            - "8080:8080"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication

    loans:
        build:
            context: ./loans  # Points to the loans directory
            dockerfile: Dockerfile.loans  # Dockerfile within the loans directory
        image: marcossata/loans:s4
        container_name: loans-ms
        ports:
            - "8090:8090"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication

    cards:
        build:
            context: ./cards  # Points to the cards directory
            dockerfile: Dockerfile.cards  # Dockerfile within the cards directory
        image: marcossata/cards:s4
        container_name: cards-ms
        ports:
            - "9000:9000"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication

networks:
    bankApplication:
        driver: bridge
