version: '3.8'

services:
    configserver:
        build:
            context: ../../configserver  # Points to the accounts directory
            dockerfile: ../../configserver/Dockerfile.config-server  # Dockerfile within the accounts directory
        image: marcossata/config-server:s6

        container_name: config-server-ms
        ports:
            - "8071:8071"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication

    accounts:
        build:
            context: ../../accounts  # Points to the accounts directory
            dockerfile: ../../accounts/Dockerfile.accounts  # Dockerfile within the accounts directory
        image: marcossata/accounts:s6

        container_name: accounts-ms
        ports:
            - "8080:8080"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication
        environment:
            SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
            SPRING_PROFILES_ACTIVE: default
            SPRING_APPLICATION_NAME: "accounts"


    loans:
        build:
            context: ../../loans  # Points to the loans directory
            dockerfile: ../../loans/Dockerfile.loans  # Dockerfile within the loans directory
        image: marcossata/loans:s6

        container_name: loans-ms
        ports:
            - "8090:8090"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication
        environment:
            SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
            SPRING_PROFILES_ACTIVE: default
            SPRING_APPLICATION_NAME: "loans"

    cards:
        build:
            context: ../../cards  # Points to the cards directory
            dockerfile: ../../cards/Dockerfile.cards  # Dockerfile within the cards directory
        image: marcossata/cards:s6

        container_name: cards-ms
        ports:
            - "9000:9000"
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - bankApplication
        environment:
            SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
            SPRING_PROFILES_ACTIVE: default
            SPRING_APPLICATION_NAME: "cards"

networks:
    bankApplication:
        driver: bridge
