server:
    port: 8090
spring:
    application:
        name: "loans"
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: false
    profiles:
        active: @spring.profiles.active@
    config:
        import:
            - "optional:configserver:http://localhost:8071"
    # rabbitmq: UNCOMENT THIS TO USE RABBITMQ - 8
    #     host: "localhost"
    #     port: 5672
    #     username: "guest"
    #     password: "guest"

management:
    endpoints:
        web:
            exposure:
                include: "*" # Enable and expose all management endpoints suport by spring Actuator