spring:
    config:
        activate:
            on-profile: "prod"

build:
    version: "3.0"

loans:
    message: "Microservice for Cards. Environment: PROD"
    contactDetails:
        name: "Marcosxx1"
        email: "marcosxx1.ma@gmail.com"
    onCallSuport:
        - (XX) XXX-XXX1
        - (XX) XXX-XXX2