spring:
    config:
        activate:
            on-profile: "qa"

build:
    version: "2.0"

loans:
    message: "Microservice for Cards. Environment: QA"
    contactDetails:
        name: "Marcosxx1"
        email: "marcosxx1.ma@gmail.com"
    onCallSuport:
        - (XX) XXX-XXX1
        - (XX) XXX-XXX2