server:
    port: 8090
spring:
    application:
        name: "loans"
    datasource:
        url: jdbc:mysql://localhost:3307/loansdb # Temporary, learning purposes, non-critical information
        username: root
        password: root
    jpa:
        show-sql: true
    sql:
        init:
            mode: always
    profiles:
        active: @spring.profiles.active@
    config:
        import:
            - "optional:configserver:http://localhost:8071"
    # rabbitmq: UNCOMENT THIS TO USE RABBITMQ - 8
    #     host: "localhost"
    #     port: 5672
    #     username: "guest"
    #     password: "guest"
management:
    endpoints:
        web:
            exposure:
                include: "*" # Enable and expose all management endpoints suport by spring Actuator