build:
    version: "3.0"

loans:
    message: "Microservice for Loans. Environment: DEFAULT"
    contactDetails:
        name: "Marcosxx1"
        email: "marcosxx1.ma@gmail.com"
    onCallSuport:
        - (XX) XXX-XXX1
        - (XX) XXX-XXX2