server:
    port: 8071

spring:
    application:
      name: "Config Server"
    profiles:
        active: native
    cloud:
      config:
        server:
          native: # The bellow path is from my machine, and it is the same as configpath,
                  # but just to learning purposes, we could've place then anywhere else
            search-locations: file:///C://Users//marco//IdeaProjects//spring-microservices//configserver//src//main//resources//config
          #search-locations: classpath:/config # < classpath
