server:
    port: 8071

spring:
    application:
      name: "Config Server"
    profiles:
        active: native
    cloud:
      config:
        server:
          native:
              search-locations: classpath:/config # < classpath